PersonalDashboard/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PersonalDashboard.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

PersonalDashboard/Pages/BlockGame.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PersonalDashboard.Pages
{
    public class BlockGameModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

PersonalDashboard/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PersonalDashboard.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

PersonalDashboard/Pages/EditNote.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace PersonalDashboard.Pages
{
    public class EditNoteModel : PageModel
    {
        private readonly NotesDbContext dbContext;

        public EditNoteModel(NotesDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [BindProperty]
        public Note Note { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Note = await dbContext.Notes.FindAsync(id);
            if (Note == null)
            {
                return RedirectToPage("./Error");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            dbContext.Attach(Note).State = EntityState.Modified;

            try
            {
                await dbContext.SaveChangesAsync();
            }
            catch(DbUpdateConcurrencyException ex)
            {
                throw new Exception($"Note: '{Note.Id}' could not be edited", ex);
            }

            return RedirectToPage("/Notes");
        }
    }
}

PersonalDashboard/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PersonalDashboard.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

PersonalDashboard/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PersonalDashboard.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

PersonalDashboard/Pages/News.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NewsProviders;

namespace PersonalDashboard.Pages
{
    public class NewsModel : PageModel
    {
        public List<NewsItem> HeiseNews { get; set; }

        public List<NewsItem> GolemNews { get; set; }

        public void OnGet()
        {
            HeiseNewsProvider heiseProvider = new HeiseNewsProvider();
            GolemNewsProvider golemProvider = new GolemNewsProvider();

            HeiseNews = heiseProvider.GetNewsItemsFromUrl("http://heise.de").ToList();
            GolemNews = golemProvider.GetNewsItemsFromUrl("http://golem.de").ToList();
        }
    }
}

PersonalDashboard/Pages/Notes.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace PersonalDashboard.Pages
{
    public class NotesModel : PageModel
    {
        private readonly NotesDbContext dbContext;


        [BindProperty]
        public IList<Note> Notes { get; set; }

        [BindProperty]
        public Note Note { get; set; }


        public NotesModel(NotesDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public async Task OnGetAsync()
        {
            Notes = await dbContext.Notes.AsNoTracking().ToListAsync();
        }

        /// <summary>
        /// Implementation of CreateNote handler to create a new note
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> OnPostCreateNoteAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            dbContext.Add(Note);

            await dbContext.SaveChangesAsync();

            return RedirectToPage("/Notes");
        }

        /// <summary>
        /// Implementation of DeleteNote handler to delete a given note
        /// </summary>
        /// <param name="id">Id of note to delete</param>
        /// <returns></returns>
        public async Task<IActionResult> OnPostDeleteNoteAsync(int id)
        {
            Note note = await dbContext.Notes.FindAsync(id);
            if (note != null)
            {
                dbContext.Notes.Remove(note);
                await dbContext.SaveChangesAsync();
            }
            return RedirectToPage("./Notes");
        }

    }
}

PersonalDashboard/Pages/BlockGame.cshtml
@page
@model PersonalDashboard.Pages.BlockGameModel

@{
    ViewData["Title"] = "BlockGame";
    Layout = "~/Pages/_Layout.cshtml";
}
<script src="~/lib/jquery/dist/jquery.js"></script>

<script src="~/js/BlockGame/BlockFactory.js"></script>
<script src="~/js/BlockGame/UpdateTimer.js"></script>
<script src="~/js/BlockGame/BlockGameMain.js"></script>

<br />
<div style="float: left; margin:0; padding:0">
    <canvas id="canvasGameArea"></canvas>
</div>
<div style="float: left; margin-left:10px;">
    <div id="textScore" style="font-size:20pt; font-weight:bold;"></div>
    <br />
    <br />
    <h2>Controls</h2><br />
    A - Move left<br />
    D - Move right<br />
    S - Move down<br />
    J - Rotate left<br />
    K - Rotate right<br />
    <br />
</div>

<br style="clear:both" />
<br />

PersonalDashboard/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PersonalDashboard/Pages/EditNote.cshtml
@page "{id:int}"

@model PersonalDashboard.Pages.EditNoteModel
@{
    ViewData["Title"] = "EditNote";
    Layout = "~/Pages/_Layout.cshtml";
}

<h2>EditNote: @Model.Note.Id</h2>

<form method="post">
    <div asp-validation-summary="All"></div>
    <input asp-for="Note.Id" type="hidden" />
    <div >
        <label asp-for="Note.Content"></label>
        <input asp-for="Note.Content" />
        <span asp-validation-for="Note.Content"></span>
    </div>
    <button type="submit">Edit</button>
</form>

PersonalDashboard/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core Razor Pages</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure App Service</a></li>
        </ul>
    </div>
</div>

PersonalDashboard/Pages/News.cshtml
@page
@model PersonalDashboard.Pages.NewsModel
@using NewsProviders
@{
    ViewData["Title"] = "News";
    Layout = "~/Pages/_Layout.cshtml";
}

<style>
    #heise_div, #golem_div {
        width: 400px;
        /*height: 100px;*/
        border: 1px solid black;
        margin: 10px;
        padding: 5px;
        float: left;
    }
</style>


<div id="heise_div">
    <h2>Heise - News</h2>
    @foreach (NewsItem heiseNewsItem in Model.HeiseNews)
    {
        <a href="@string.Format("http://heise.de{0}", heiseNewsItem.Link)">
            <div style="font-size: 14px; font-weight:bold">@heiseNewsItem.Title</div><br />
        </a>
        <div>@Html.Raw(heiseNewsItem.Teaser)</div>
        <br />
    }
</div>

<div id="golem_div">
    <h2>Golem - News</h2>
    @foreach (NewsItem golemNewsItem in Model.GolemNews)
    {
        <a href="@string.Format("http://golem.de{0}", golemNewsItem.Link)">
            <div style="font-size: 14px; font-weight:bold">@Html.Raw(golemNewsItem.Title)</div><br />
        </a>
        <div>@Html.Raw(golemNewsItem.Teaser)</div>
        <br />
    }
</div>
<br style="clear:both" />

PersonalDashboard/Pages/Notes.cshtml
@page
@model PersonalDashboard.Pages.NotesModel
@{
    ViewData["Title"] = "Notes";
    Layout = "~/Pages/_Layout.cshtml";
}

<h2>Notes</h2>
<!-- Display notes -->
<form method="post">
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Note note in Model.Notes)
            {
                <tr>
                    <td>@note.Id</td>
                    <td id="@string.Format("note-id-{0}", @note.Id)">@note.Content</td>
                    <td>
                        <a asp-page="./EditNote" asp-route-id="@note.Id">Edit</a>
                        <button type="submit" asp-page-handler="DeleteNote" asp-route-id="@note.Id">Delete</button>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</form>

<!-- Create note -->
<form method="post">
    <div asp-validation-summary="All"></div>
    <p>NoteContent</p>
    <input asp-for="Note.Content">
    <br />
    <button type="submit" asp-page-handler="CreateNote">Create</button>
</form>

PersonalDashboard/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PersonalDashboard</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">PersonalDashboard</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/News">News</a></li>
                    <li><a asp-page="/Notes">Notes</a></li>
                    <li><a asp-page="/BlockGame">BlockGame</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - PersonalDashboard</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>